# Generated by Django 4.2.7 on 2023-11-13 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('passw', models.CharField(max_length=100)),
                ('ip', models.CharField(max_length=100)),
            ],
        ),
    ]
