# Generated by Django 4.2.7 on 2023-11-13 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_port_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='port',
            name='powerLevel',
            field=models.TextField(blank=True, null=True),
        ),
    ]
